### ISSUE TITLE
Apple TV 2 

### ISSUE THREAD

**Issue by jfbourne** [k3oni/script.xbmc.pandora#1]
Work perfect in XBMC Windows and it loads fine on Apple TV; hower it does not play any station (on Apple TV). I select station, press play and still nothing.. Is there any support for apple tv?

PS.  Thanks for this contribution.
Great Work.

**Comment by k3oni** [comment]
What is the audio format in the addon settings? Try to set it to mp3 or aacplus.

**Comment by jfbourne** [comment]
Awesome thanks a lot.. That work!!!
